############################
# Database
############################
spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_HOST_PORT:5433}/${POSTGRES_DB:rockskay}
spring.datasource.username=${POSTGRES_USER:rockskay}
spring.datasource.password=${POSTGRES_PASSWORD:RockSkay@2026}

############################
# JPA
############################

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

############################
# Flyway
############################

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

############################
# Logging
############################

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE