############################
# Database
############################

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

############################
# JPA
############################

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

############################
# Flyway
############################

spring.flyway.enabled=true

############################
# JWT
############################
app.jwt.key=${JWT_SECRET_KEY}
app.jwt.accessToken.expiresInMin=${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
app.jwt.refreshToken.expiresInMin=${JWT_REFRESH_TOKEN_EXPIRE_MINUTES}
app.jwt.issuer=${JWT_ISSUER}